### ISSUE TITLE
Error installing: InMemoryUser / LiveComponents

### ISSUE THREAD

**Issue by tacman** [SymfonyCasts/netgen-layouts#14]
```bash
git clone git@github.com:SymfonyCasts/netgen-layouts.git && cd netgen-layouts
composer install
```

There is no user provider for user "Symfony\Component\Security\Core\User\InMemoryUser". Shouldn't the "supportsClass()" method of your user provider return true for this classname?

Updating to the latest libraries then thows an error about LiveComponents:

```bash
composer update
```

Unable to find file "@LiveComponentBundle/Resources/config/routing/live_component.xml" in @LiveComponentBundle/Resources/config/routing/live_component.xml (which is being imported from "/home/tac/g/tacman/netgen-layouts/config/routes/ux_live_component.yaml"). Make sure the "LiveComponentBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@LiveComponentBundle/Resources/config/routing/live_component.xml" is not empty.

**Comment by bocharsky-bw** [comment]
Hey @tacman ,

We do not encourage users to clone our course project GitHub repos. Instead, we encourage to download the course code on a course chapter page. That will give you a zip file with start/ and finish/ folders inside. You can start with the start/ folder to follow the course.

The problem is that some tutorials may have some precondition steps that were done with internal tools and are not available in the GitHub repo when you clone it directly - it just depends on our process of creating tutorials.

Cheers!

**Comment by tacman** [comment]
OK, so I've download the source code from the sfcasts site, started docker, follow the installation instructions and loaded the database.  And then started the symfony server.

Alas, when I go to the homepage (or /login or /admin or /cb), the webpage simply times out.

It looks like the contentful api key is no longer valid (in .env), but that shouldn't prevent login or the other pages from working (I'm guessing).

composer update is my go-to for this kind of things, but too many things have changes that throws errors.

The reason I haven't walked through the course yet is that I almost always start at the end -- does it install and work on my computer?  When I see it working, do I say "Oh, wow, I want that!"  

I'm using PHP 8.3, perhaps the deprecated INI issue is causing the problem?  Is there a single package I can update to get this to work out of the box?  

Thanks

**Comment by tacman** [comment]
Ignore all that.  I dunno what the problem was, but 

composer update symfony/runtime

and now I can log in.  No layouts, though, and really no pages, but that's probably related to the contentful api key, which when I go through the tutorial I'm sure I'll learn.

**Comment by bocharsky-bw** [comment]
Hey @tacman ,

OK, I'm glad to hear it works for you. Hm, not sure... I just downloaded the course code and loaded the project well from the start/ dir, it works for me on PHP 8.1. If you ever stuck somewhere following our tutorials - feel free to let us know in the comments below the video and our support team will help you.

Cheers!
